<a href="https://colab.research.google.com/github/grnbatera/TFC/blob/main/TFC_1_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/grnbatera/TFC.git

Cloning into 'TFC'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.


In [2]:
#Instalando módulo i/o do tensorflow
!pip install -q tensorflow-io

     |████████████████████████████████| 25.3MB 1.6MB/s 


In [3]:
!pip install matlab

  Created wheel for matlab: filename=matlab-0.1-cp36-none-any.whl size=1180 sha256=5f38517b7b2c29d92d6292a1441625fe4286b02ded7aa3ef32ab630cd3538d96
  Stored in directory: /root/.cache/pip/wheels/fe/ea/9a/2d99da71ec929e083a47e62aa641d25c95cb0cb32fb288b817
Successfully built matlab


In [4]:
#importando bibliotecas
%matplotlib inline  
import matplotlib.pyplot as plt #importa o pacote de plotagem
import numpy as np #pacote numpy faz manipulações numéricas
from IPython.display import Audio #importando ferramentas de audio
import librosa #importando biblioteca de ferramentas amplas de manipulação de audio
import librosa.display #importando ferramentas de spectograma do librosa
import librosa.feature
import pandas as pd
import math
import seaborn as sns
import matplotlib as mpl
import tensorflow as tf
import tensorflow_io as tfio
import matlab
import scipy
from scipy import signal

In [5]:
'''
mpl.rcParams['font.family'] = 'Roboto'
plt.rcParams['font.family'] = 'Roboto'
sns.set(font='Roboto',
        rc={
 'axes.axisbelow': False,
 'axes.edgecolor': 'lightgrey',
 'axes.facecolor': 'None',
 'axes.grid': False,
 'axes.labelcolor': 'dimgrey',
 'axes.spines.right': False,
 'axes.spines.top': False,
 'figure.facecolor': 'white',
 'lines.solid_capstyle': 'round',
 'patch.edgecolor': 'w',
 'patch.force_edgecolor': True,
 'text.color': 'black',
 'xtick.bottom': False,
 'xtick.color': 'dimgrey',
 'xtick.direction': 'out',
 'xtick.top': False,
 'ytick.color': 'dimgrey',
 'ytick.direction': 'out',
 'ytick.left': False,
 'ytick.right': False})
 
sns.set_context("notebook", rc={"font.size":20,
                                "axes.titlesize":24,
                                "axes.labelsize":18})
                                '''

'\nmpl.rcParams[\'font.family\'] = \'Roboto\'\nplt.rcParams[\'font.family\'] = \'Roboto\'\nsns.set(font=\'Roboto\',\n        rc={\n \'axes.axisbelow\': False,\n \'axes.edgecolor\': \'lightgrey\',\n \'axes.facecolor\': \'None\',\n \'axes.grid\': False,\n \'axes.labelcolor\': \'dimgrey\',\n \'axes.spines.right\': False,\n \'axes.spines.top\': False,\n \'figure.facecolor\': \'white\',\n \'lines.solid_capstyle\': \'round\',\n \'patch.edgecolor\': \'w\',\n \'patch.force_edgecolor\': True,\n \'text.color\': \'black\',\n \'xtick.bottom\': False,\n \'xtick.color\': \'dimgrey\',\n \'xtick.direction\': \'out\',\n \'xtick.top\': False,\n \'ytick.color\': \'dimgrey\',\n \'ytick.direction\': \'out\',\n \'ytick.left\': False,\n \'ytick.right\': False})\n \nsns.set_context("notebook", rc={"font.size":20,\n                                "axes.titlesize":24,\n                                "axes.labelsize":18})\n                                '

In [6]:
a1 = [1, -0.3];
g = .995;
b1 = g * 0.7
b1


0.6965

In [7]:
fname1='/content/TFC/body1.wav'
#pegando os valores de sr e atribuindo audio para y
y1, fs=librosa.load(fname1, sr=None, mono=True) #lendo o fname, se sr diferente de None ele reamostra pra 22050 Hz

In [8]:
y1
Audio(data=y1,rate=fs)

In [9]:
y1=pd.DataFrame(y1)
y1=np.array(y1).reshape(1,8192)


In [10]:
Audio(data=y1,rate=fs)

In [11]:
fs

22050

In [12]:
f=440
phi=0.4275
D = math.floor(fs/f - phi);
d = fs/f - phi - D;

if d < 0.1:
  d = d + 1;
  D = D - 1;

In [13]:
eta = (1-d) / (1+d);
b2 = [eta,1];
a2 = [1,eta];


In [14]:
num=np.convolve(b1,b2)
den=np.convolve(a1,a2)
den

array([ 1.        , -0.11385631, -0.05584311])

In [15]:
num

array([0.12964908, 0.6965    ])

In [17]:
b=den
z=-num
m=matlab.zeros((k,))
a=np.hstack((b,m,z))
a

array([ 1.        , -0.11385631, -0.05584311,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , -0.12964908,
       -0.6965    ])

In [18]:
DUR=3

In [19]:
z1=matlab.zeros((1,DUR*fs-len(y1)));
z1
x=np.hstack((y1,z1))

In [20]:
y = scipy.signal.lfilter(b, a, x, axis=0);

#Normalize y 
y = y/(max(abs(y))+.1);
y

array([[-0.01856955,  0.00636788, -0.02875096, ...,  0.        ,
         0.        ,  0.        ]])

In [21]:
Audio(data=x,rate=fs)

In [22]:
matlab.siz

AttributeError: ignored